-- 1번 : DDL 테이블 구조 변경

SELECT * FROM TBL_SHOP_USER

DROP TABLE TBL_MEMBER;

-- 1) 테이블 이름변경
ALTER TABLE TBL_SHOP_USER 
RENAME TO TBL_MEMBER;

-- 테이블이름 확인
SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME LIKE 'TBL%';

-- 2) 컬럼 이름 변경
SELECT * FROM TBL_MEMBER;

ALTER TABLE TBL_MEMBER
RENAME COLUMN NAME TO ID;

ALTER TABLE TBL_MEMBER
RENAME COLUMN USER_NAME TO NAME;

-- 3)
ALTER TABLE TBL_MEMBER
MODIFY (NAME VARCHAR(100)); -- 길이 늘리는 것 가능, 크기를 줄일 때는 데이터가 있으면 에러남

SELECT * FROM TBL_MEMBER;

--ALTER TABLE TBL_MEMBER
--MODIFY (GENDER VACHAR2(1));

-- 4) 전화번호 컬럼 추가
ALTER TABLE TBL_MEMBER
ADD (PHONE VARCHAR2(20));

-- 포인트
ALTER TABLE TBL_MEMBER
ADD(POINT NUMBER DEFAULT '0');
-- 5) 컬럼 삭제
ALTER TABLE TBL_MEMBER
DROP COLUMN POINT;

--6) 제약조건 추가
INSERT INTO TBL_MEMBER
VALUES(2, '신짜구', 'gu@test.com', 'M', 'Y', SYSDATE, '010-1234-1234',NULL);

UPDATE TBL_MEMBER
SET POINT = 0;

-- NOT NULL 제약조건 추가는 MODIFY로 함
ALTER TABLE TBL_MEMBER
MODIFY (POINT NOT NULL);

-- 핸드폰에 UNIQUE 추가
ALTER TABLE TBL_MEMBER
ADD CONSTRAINT UK_MEMBER_PHONE UNIQUE (PHONE);

-- 7) 제약조건 삭제
ALTER TABLE TBL_MEMBER
DROP CONSTRAINT UK_MEMBER_PHONE;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TBL_MEMBER';

SELECT * FROM TBL_MEMBER;

ALTER TABLE TBL_MEMBER
--DROP CONSTRAINT SYS_C007005;
--DROP CONSTRAINT UN_EMAIL;
--DROP CONSTRAINT PK_SHOP_USER;
--DROP CONSTRAINT CHK_STATUS;
--DROP CONSTRAINT CHK_GENDER;
DROP CONSTRAINT SYS_C007000;

