-- 3번 : 모델링

--	TBL_PHONE
--	PHONE_NUMBER	NUMBER		PRIMARY KEY
--	-------------------------------------------
--	PHONE_COLOR	VARCHAR2(20)	NN
--	PHONE_SIZE	VARCHAR2(20)	NN
--	PHONE_PRICE	NUMBER		NN
--	PHONE_DATE	DATE		NN
--	PHONE_DISCOUNT	NUMBER(3, 2)	NN
--
--	CASE
--	CASE_NUMBER	NUMBER		PK
--	CASE_COLOR	VARCHAR2	NN
--	CASE_PRICE	NUMBER		NN
--	PHONE_NUMBER	NUMBER		FK

CREATE TABLE TBL_PHONE(
	PHONE_NUMBER NUMBER,
	PHONE_COLOR	VARCHAR2(20) NOT NULL,
	PHONE_SIZE	VARCHAR2(20)NOT NULL,
	PHONE_PRICE	NUMBER NOT NULL,
	PHONE_DATE	DATE NOT NULL,
	PHOEN_DISCOUNT NUMBER(3, 2)NOT NULL,
	CONSTRAINT PK_PHONE PRIMARY KEY(PHONE_NUMBER)
);

CREATE TABLE TBL_CASE(
	CASE_NUMBER	NUMBER,		
	CASE_COLOR	VARCHAR2(20) NOT NULL,	
	CASE_PRICE	NUMBER NOT NULL,
	PHONE_NUMBER NUMBER,
	CONSTRAINT PK_CASE PRIMARY KEY(CASE_NUMBER),
	CONSTRAINT FK_PHONE_CASE FOREIGN KEY(PHONE_NUMBER) REFERENCES TBL_PHONE(PHONE_NUMBER)
);

SELECT * FROM TBL_PHONE;
SELECT * FROM TBL_CASE;

