-- 2번 : 집합


CREATE TABLE TBL_A(
   NAME VARCHAR2(20)
);

INSERT INTO TBL_A VALUES('홍길동');
INSERT INTO TBL_A VALUES('김보라');
INSERT INTO TBL_A VALUES('김나나');
INSERT INTO TBL_A VALUES('김뚜비');
INSERT INTO TBL_A VALUES('이철수');

CREATE TABLE TBL_B (
   NAME VARCHAR2(20)
);

INSERT INTO TBL_B VALUES('이철수');
INSERT INTO TBL_B VALUES('심호동');
INSERT INTO TBL_B VALUES('이지민');
INSERT INTO TBL_B VALUES('이영희');
INSERT INTO TBL_B VALUES('김뚜비');

SELECT * FROM TBL_A;
SELECT * FROM TBL_B;

-- 1) UNION : 합집합, 중복제거 => 결과는 중복 없이 모든 이름 표시
SELECT NAME FROM TBL_A
UNION
SELECT NAME FROM TBL_B; -- 중복 제거되므로 8행

-- 2) UNION ALL : 합집합, 중복 제거되지 않음
SELECT NAME FROM TBL_A
UNION ALL
SELECT NAME FROM TBL_B; -- 중복제거되 않으므로 10행

-- 3) INTERSECT : 교집합(A와 B에 모두 있는 사람만 출력)
SELECT NAME FROM TBL_A
INTERSECT
SELECT NAME FROM TBL_B; -- 2행

-- 4) MINUS : 차집합
SELECT NAME FROM TBL_A
MINUS
SELECT NAME FROM TBL_B; -- 3행

SELECT NAME FROM TBL_B
MINUS
SELECT NAME FROM TBL_A; -- 3행

-- HR계정으로 접근
SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

-- 1) 급여가 10000 이상 또는 SA_REP 직무를 가진 직원의 목록을 합쳐서 조회(중복 제외)
SELECT * FROM EMPLOYEES WHERE SALARY >= 10000 -- 19행
UNION 
SELECT * FROM EMPLOYEES WHERE JOB_ID = 'SA_REP'; -- 30행

-- 2) Roma 지역에서 근무하는 부서의 소속 직원 중 급여가 5000 이상인 직원만 조회
-- EMPLOYEES 직원, DEPARTMENTS 부서, LOCATIONS 지역
-- 조회컬럼 : EMPLOYEE_ID, FIRST_NAME, SALARY, DEPARTMENT_NAME, CITY
-- 집합연산 필요 없음 => JOIN, WHERE AND 연산자
SELECT * FROM LOCATIONS l ;
SELECT * FROM EMPLOYEES e ;
SELECT * FROM DEPARTMENTS d ;
SELECT E.EMPLOYEE_ID ,E.FIRST_NAME ,E.SALARY , D.DEPARTMENT_NAME ,L.CITY  
FROM DEPARTMENTS d  
JOIN LOCATIONS l ON D.LOCATION_ID = L.LOCATION_ID 
JOIN EMPLOYEES e ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
WHERE L.CITY = 'Roma' AND E.SALARY >= 5000;

-- 3) 모든 직원 목록 중에서 부서 배정 안 된 직원만 조회
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NULL;

-- 4) 급여가 9000이상인 직원과 부서번호가 50번인 직원을 중복 포함해서 조회
-- 조회컬럼 : EMPLOYEE_ID, FIRST_NAME, SALARY, DEPARTMENT_ID
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES e WHERE SALARY >= 9000
UNION ALL
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, DEPARTMENT_ID  FROM EMPLOYEES WHERE DEPARTMENT_ID = 50;

-- 집합연산 규칙 : 컬럼개수가 같아야함, 순서가 같아야함, 타입이 맞아야함
-- 따라서 SELECT * 로 사용하는 것은 위험함(컬럼이 바뀔경우 바로 오류발생)










