-- 급여가 평균 급여보다 높은 직원 조회

-- 1)평균 급여 먼저 구하기
SELECT AVG(SALARY) FROM EMPLOYEES;

-- 2)결과를 조건으로 사용
SELECT * FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

-- 직원의 이름과 그 직원이 속한 부서명을 조회

SELECT FIRST_NAME, DEPARTMENT_NAME
FROM EMPLOYEES e 
JOIN DEPARTMENTS d ON D.DEPARTMENT_ID = E.DEPARTMENT_ID ;

-- 직원의 이름, 급여, 직무명을 조회하시오.
SELECT * FROM JOBS j ;

SELECT FIRST_NAME, SALARY, JOB_TITLE
FROM EMPLOYEES e 
JOIN JOBS j ON E.JOB_ID = J.JOB_ID ;

-- 부서명과 해당 부서에 속한 직원의 이름, 입사일을 조회하시오.
-- 단, 직원이 없는 부서는 제외
SELECT * FROM DEPARTMENTS d ;
SELECT * FROM EMPLOYEES e ;

SELECT DEPARTMENT_NAME, FIRST_NAME, HIRE_DATE
FROM DEPARTMENTS d 
JOIN EMPLOYEES e ON E.DEPARTMENT_ID = D.DEPARTMENT_ID ;

